version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: joblinker-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345Thanh
      MYSQL_DATABASE: joblinker
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - joblinker-network

  joblinker:
    image: joblinker:latest
    container_name: joblinker-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/joblinker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345Thanh

      # Mail
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      # OAuth2
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      # Cloudinary
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      JWT_SECRET: ZVRqZjVDa3B3U3R3b0RjVmdUNnBVcTl3QlJ1Qm5LTXlMVll3aFFsOWRmclJKZmtTRnF0c29uVlJSYmE1YjJzaw\=\=

    networks:
      - joblinker-network
volumes:
  mysql_data:

networks:
  joblinker-network: